"""PNG icon → TFT RGB565 / U8g2 XBM header generation (matches app.js conventions)."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Literal

from fastapi import APIRouter, HTTPException
from PIL import Image
from pydantic import BaseModel, Field

MAX_ICONS_PER_REQUEST = 400


def infer_size_from_path(file_path: str) -> tuple[int, int] | None:
    raw = file_path.replace("\\", "/")
    for part in raw.split("/"):
        m = re.match(r"^(\d+)x(\d+)$", part, re.I)
        if m:
            w, h = int(m.group(1)), int(m.group(2))
            if w > 0 and h > 0:
                return w, h
    return None


def safe_symbol_from_path(path: str) -> str:
    raw = path.replace("\\", "/")
    base = raw.split("/")[-1] or raw
    no_ext = re.sub(r"\.[a-z0-9]+$", "", base, flags=re.I)
    sym = re.sub(r"[^a-zA-Z0-9_]", "_", no_ext)
    return sym or "icon"


def hex_to_rgb(hex_str: str) -> tuple[int, int, int]:
    s = (hex_str or "#000000").strip().lstrip("#")
    if len(s) == 6:
        return int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)
    return 0, 0, 0


def rgba_to_rgb565_row(
    rgba: bytes, w: int, h: int, bg: tuple[int, int, int]
) -> list[int]:
    """Same alpha rule as app.js imageDataToRgb565 (alpha < 16 → background)."""
    out: list[int] = []
    bg_r, bg_g, bg_b = bg
    for p in range(w * h):
        i = p * 4
        r, g, b, a = rgba[i], rgba[i + 1], rgba[i + 2], rgba[i + 3]
        if a < 16:
            r, g, b = bg_r, bg_g, bg_b
        r5 = (r >> 3) & 0x1F
        g6 = (g >> 2) & 0x3F
        b5 = (b >> 3) & 0x1F
        out.append((r5 << 11) | (g6 << 5) | b5)
    return out


def rgba_to_mono_xbm(rgba: bytes, w: int, h: int) -> bytes:
    """LSB-first within byte, row-major; same thresholds as app.js buildMonoBitmapFromImageData."""
    alpha_threshold = 16
    luma_threshold = 0.35
    bytes_per_row = (w + 7) // 8
    buf = bytearray(bytes_per_row * h)
    for y in range(h):
        for x in range(w):
            i = (y * w + x) * 4
            r, g, b, a = rgba[i], rgba[i + 1], rgba[i + 2], rgba[i + 3]
            lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255.0
            if a >= alpha_threshold and lum >= luma_threshold:
                bi = y * bytes_per_row + (x >> 3)
                buf[bi] |= 1 << (x & 7)
    return bytes(buf)


def resolve_icon_file(static_root: Path, rel_file: str) -> Path:
    rel = rel_file.replace("\\", "/").lstrip("/")
    if not rel or ".." in rel.split("/"):
        raise ValueError("invalid icon path")
    icons_root = (static_root / "icons").resolve()
    full = (icons_root / rel).resolve()
    try:
        full.relative_to(icons_root)
    except ValueError as e:
        raise ValueError("icon path escapes icons directory") from e
    return full


def load_rgba_resized(path: Path, tw: int, th: int) -> tuple[int, int, bytes]:
    with Image.open(path) as im:
        im = im.convert("RGBA")
        nw, nh = im.size
        if tw <= 0 or th <= 0:
            raise ValueError("Invalid icon dimensions.")
        if (nw, nh) != (tw, th):
            im = im.resize((tw, th), Image.Resampling.LANCZOS)
        raw = im.tobytes()
    return tw, th, raw


class IconRef(BaseModel):
    file: str = Field(..., description="Path under icons/, e.g. 16x16/wifi_1.png")


class IconExportRequest(BaseModel):
    mode: Literal["tft_rgb565", "u8g2_xbm"]
    bg_color: str = "#000000"
    icons: list[IconRef] = Field(..., min_length=1)


def build_icons_router(static_root: Path) -> APIRouter:
    router = APIRouter(prefix="/api/icons", tags=["icons"])

    @router.post("/export")
    def export_icons(body: IconExportRequest) -> dict[str, str | bool]:
        if len(body.icons) > MAX_ICONS_PER_REQUEST:
            raise HTTPException(
                status_code=400,
                detail=f"Too many icons (max {MAX_ICONS_PER_REQUEST}).",
            )

        bg = hex_to_rgb(body.bg_color)
        lines: list[str] = []

        if body.mode == "tft_rgb565":
            lines.append("// Auto-generated by DisplayKit (Icon List → Export TFT, server)\n")
            lines.append("#pragma once\n\n")
            lines.append("#include <Arduino.h>\n")
            lines.append("#include <pgmspace.h>\n\n")
            lines.append(
                "// Note: any transparent pixels are mapped to the current DisplayKit background color.\n\n"
            )
            filename = "displaykit_icons_rgb565.h"
        else:
            lines.append("// Auto-generated by DisplayKit (Icon List → Export U8g2, server)\n")
            lines.append("#pragma once\n\n")
            lines.append("#include <Arduino.h>\n")
            lines.append("#include <pgmspace.h>\n\n")
            lines.append("// Use with: u8g2.drawXBMP(x, y, w, h, <name>);\n\n")
            filename = "displaykit_icons_xbm.h"

        for ref in body.icons:
            rel = ref.file.strip()
            try:
                path = resolve_icon_file(static_root, rel)
            except ValueError as e:
                lines.append(f"// {rel}\n")
                lines.append(f"// ERROR: {e}\n\n")
                continue
            if not path.is_file():
                lines.append(f"// {rel}\n")
                lines.append("// ERROR: file not found\n\n")
                continue

            inferred = infer_size_from_path(rel)
            try:
                with Image.open(path) as probe:
                    probe = probe.convert("RGBA")
                    nw, nh = probe.size
                tw, th = inferred if inferred else (nw, nh)
                tw, th, rgba = load_rgba_resized(path, tw, th)
            except Exception as e:  # noqa: BLE001 — surface as C comment
                lines.append(f"// {rel}\n")
                lines.append(f"// ERROR: {e}\n\n")
                continue

            sym = safe_symbol_from_path(rel)
            if body.mode == "tft_rgb565":
                words = rgba_to_rgb565_row(rgba, tw, th, bg)
                name = f"icon_{sym}_{tw}x{th}"
                total = tw * th
                lines.append(f"// {rel}\n")
                lines.append(f"const uint16_t {name}[{total}] PROGMEM = {{\n")
                for i, wv in enumerate(words):
                    is_last = i == len(words) - 1
                    if i % 12 == 0:
                        lines.append("  ")
                    lines.append(f"0x{wv & 0xFFFF:04X}")
                    lines.append("" if is_last else ", ")
                    if i % 12 == 11 or is_last:
                        lines.append("\n")
                lines.append("};\n\n")
            else:
                mono = rgba_to_mono_xbm(rgba, tw, th)
                name = f"icon_{sym}_{tw}x{th}_xbm"
                lines.append(f"// {rel}\n")
                lines.append(f"#define {name}_width {tw}\n")
                lines.append(f"#define {name}_height {th}\n")
                lines.append(f"const unsigned char {name}[{len(mono)}] PROGMEM = {{\n")
                for i, bv in enumerate(mono):
                    is_last = i == len(mono) - 1
                    if i % 16 == 0:
                        lines.append("  ")
                    lines.append(f"0x{bv & 0xFF:02X}")
                    lines.append("" if is_last else ", ")
                    if i % 16 == 15 or is_last:
                        lines.append("\n")
                lines.append("};\n\n")

        return {"ok": True, "filename": filename, "content": "".join(lines)}

    return router
